[server]
address = ":8080"
price_denom = "htltbcbusd"
handle_farms_worker_num = 11

[mongodb]
node_uri= "mongodb://iris:irispassword@127.0.0.1:27018/?connect=direct&authSource=dapp-server"
database= "dapp-server"

[redis]
address = "127.0.0.1:6379"
db = 0
password = ""

[irishub]
chain_name ="Irishub"
chain_id = "test"
#optional
base_denom = "uiris"
fee = "100000uiris"
grpc_address = "192.168.150.60:29090"
rpc_address = "tcp://192.168.150.60:26657"
lcd_address = "http://192.168.150.60:1317"

[task]
enable = true
cron_time_update_total_volume_lock = 5
cron_time_update_liquidity_pool = 5
cron_time_update_farm = 5
